// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFHdV43Wt5q9nIDPW6ohEv57taobUa6lw',
    appId: '1:618605476142:web:374f07918a14aa0f3b22bf',
    messagingSenderId: '618605476142',
    projectId: 'countero',
    authDomain: 'countero.firebaseapp.com',
    storageBucket: 'countero.appspot.com',
    measurementId: 'G-WPKRWJXGVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Doieu93dx9EG8h3b2Oz1BZ0opdl5IAI',
    appId: '1:618605476142:android:d6f1c90c64ae16ad3b22bf',
    messagingSenderId: '618605476142',
    projectId: 'countero',
    storageBucket: 'countero.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFA1UeVP4GVkOtE5NTUEXefcqG_3LvN50',
    appId: '1:618605476142:ios:de2ee337a44578d83b22bf',
    messagingSenderId: '618605476142',
    projectId: 'countero',
    storageBucket: 'countero.appspot.com',
    androidClientId: '618605476142-a6ovcnte61qaege9o70a5nr9ccra9inc.apps.googleusercontent.com',
    iosClientId: '618605476142-4aj5sumbgf8pkomm18qabm69dpafqjlp.apps.googleusercontent.com',
    iosBundleId: 'com.example.counterofferv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFA1UeVP4GVkOtE5NTUEXefcqG_3LvN50',
    appId: '1:618605476142:ios:31e5af068195903e3b22bf',
    messagingSenderId: '618605476142',
    projectId: 'countero',
    storageBucket: 'countero.appspot.com',
    androidClientId: '618605476142-a6ovcnte61qaege9o70a5nr9ccra9inc.apps.googleusercontent.com',
    iosClientId: '618605476142-5unoa0b45g1djb30p02raoivev2c4jnh.apps.googleusercontent.com',
    iosBundleId: 'com.example.counterofferv2.RunnerTests',
  );
}
